version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
      - "67:67/udp"
      - "8070:80/tcp"
    environment:
      TZ: 'Europe/Paris'
      # WEBPASSWORD: 'set a secure password here or it will be random'
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole/:/etc/pihole/'
      - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    # Recommended but not required (DHCP needs NET_ADMIN)
    #   https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    #    cap_add:
    #  - NET_ADMIN
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.16.5.0/24
