# config file version
apiVersion: 1

deleteDatasources:
  - name: loki-ne

datasources:
- name: loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: false    
