version: "3"

services:
  server:
    image: internetsystemsconsortium/bind9:9.11
    container_name: bind9
    restart: unless-stopped 
    volumes:
      - ./bind:/etc/bind
      - ./resolv.conf:/etc/bind/resolv.conf
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
    - 10.20.1.20:53:53/udp
    - 10.20.1.20:53:53/tcp            
#   - "53:53/udp"
#   - "53:53/tcp"
    - "8053:8053/tcp"

#Your NFS volume 

volumes:
  bind_vol:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.20.1.2,rw,nolock
      device: ":/bind"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.16.3.0/24

