version: "2.1"
services:
  habridge:
    image: ghcr.io/linuxserver/habridge
    container_name: habridge
    environment:
      - PUID=1000
      - PGID=1000
      - SEC_KEY=<Your Key To Encrypt Security Data>
      - TZ=Europe/Paris
    volumes:
      - ./config:/config
    ports:
      - 80:8080
      - 50000:50000
    restart: unless-stopped

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.16.4.0/24    
