version: '3'
services:
  app:
   #image: nextcloud:stable-apache
    build: .
    restart: always
    ports:
      - 8090:80
    volumes:
      - ./nextcloud:/var/www/html
      #- ./smb.sh:/smb.sh
networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  172.16.2.0/24
